version: '3'
services:
  redis:
    image: redislabs/redisearch
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - /home/ilya/Documents/yabs/db:/data

  service:
    build: .
    image: yabs_service
    ports:
      - "0.0.0.0:8080:8080"
