version: '3'
services:
  redis:
    image: redislabs/redisearch:latest
    volumes:
      - ./db:/data
      - /tmp:/tmp
    command: redis-server /data/redis.conf --loadmodule /usr/lib/redis/modules/redisearch.so
    network_mode: 'host'

  service:
    build: .
    image: yabs_service
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - redis
    volumes:
      - /tmp:/tmp

  nginx:
    image: nginx
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - service
    depends_on:
      - service
