FROM python:3.8-slim
COPY requirements_test.txt /
RUN pip install -r requirements_test.txt
COPY api /api
COPY models /models
COPY orm /orm
COPY tests /tests
RUN mypy api models orm tests
CMD  python3.8 -m unittest discover -s tests